apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocket-validator.fullname" . }}
  labels:
    {{- include "pocket-validator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.consensus }}
      name: consensus
    - port: {{ .Values.service.ports.rpc }}
      name: rpc
    - port: {{ .Values.service.ports.rpc }}
      name: metrics
  selector:
    {{- include "pocket-validator.selectorLabels" . | nindent 4 }}
